In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [2]:
x = torch.arange(4)
torch.save(x, 'x-file')

In [3]:
x2 = torch.load('x-file')
x2

tensor([0, 1, 2, 3])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'x-files')
x2, y2 = torch.load('x-files')


In [5]:
x2, y2

(tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.]))

In [7]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)

    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))

net = MLP()
X = torch.randn(size=(2, 20))
Y = net(X)

In [8]:
Y

tensor([[ 0.0076, -0.3274,  0.2823,  0.0858,  0.0936, -0.3478, -0.0677,  0.0731,
          0.0861, -0.5002],
        [-0.1035, -0.2394,  0.4083,  0.2177,  0.1640, -0.4782,  0.6519,  0.2301,
         -0.2382, -0.1764]], grad_fn=<AddmmBackward0>)

In [9]:
torch.save(net.state_dict(), 'mlp.params')

In [10]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [11]:
Y_clone = clone(X)
Y == Y_clone

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])