In [1]:
import torch

In [2]:
x = torch.arange(4)

In [3]:
x

tensor([0, 1, 2, 3])

In [4]:
x.shape

torch.Size([4])

In [5]:
A = torch.arange(20).reshape(5, 4)

In [6]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [7]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [8]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [9]:
B.T == B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [10]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [11]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [12]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [13]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [14]:
A.shape

torch.Size([5, 4])

In [16]:

A_sum_axis0=A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [17]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [18]:
A_sum_axis1=A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [19]:
A.sum(axis=[0, 1])

tensor(190.)

In [20]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [21]:
A.numel()

20

In [22]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [23]:
sum_A.shape

torch.Size([5, 1])

In [24]:
A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [25]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [30]:
x=torch.arange(4, dtype=torch.float32)
y=torch.ones(4, dtype=torch.float32)

x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [31]:
A.shape, x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [32]:
torch.mv(A, x)

tensor([ 14.,  38.,  62.,  86., 110.])

In [33]:
B = torch.ones(4, 3)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [34]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [35]:
torch.norm(torch.ones(4, 9))

tensor(6.)

In [36]:
# 证明一个矩阵A的转置的转置是A。
A = torch.randn(4, 3)
B = A.T.T
torch.equal(A, B)

True

In [38]:
# 给出两个矩阵A和B，证明它们转置的和等于它们和的转置。
A = torch.randn(4, 3)
B = torch.randn(4, 3)

torch.equal((A+B).T, A.T+B.T)

True

In [39]:
a = torch.arange(24).reshape(2, 3, 4)
len(a)

2

In [43]:
A/A.sum(axis=1, keepdim=True)

tensor([[ 4.6982, -1.7796, -1.9186],
        [-0.0418,  0.0794,  0.9624],
        [ 0.3266, -0.1201,  0.7935],
        [-0.1370,  0.1982,  0.9388]])

In [44]:
a.sum(axis=0).shape

torch.Size([3, 4])

In [45]:
a.sum(axis=1).shape

torch.Size([2, 4])